name: 自动获取硬币

on:
  workflow_dispatch: # 允许在 Actions 页面手动触发此工作流，方便测试
  schedule:
    - cron: '18 0 * * *'

jobs:
  add_time:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境上运行

    # 授予工作流写入仓库内容的权限
    permissions:
      contents: write

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Install requirements.txt
        run: |
          sudo apt update
          sudo apt install -y \
              libnss3 \
              libatk-bridge2.0-0 \
              libdrm2 \
              libxkbcommon0 \
              libgbm1 \
              libasound2t64 \
              libatspi2.0-0 \
              libxshmfence1 \
              libx11-xcb1 \
              libxrandr2 \
              libxcomposite1 \
              libxcursor1 \
              libxdamage1 \
              libxfixes3 \
              libxi6 \
              libgtk-3-0t64 \
              libatk1.0-0t64 \
              libcairo-gobject2 \
              libgdk-pixbuf-2.0-0 \
              fonts-noto-color-emoji \
              xvfb
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          playwright install 

      - name: Export all secrets to env vars
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Start noVNC 
        run: |
          sudo bash runnovnc.sh
      - name: Wait for noVNC
        run: |
          for i in {1..60}; do
            if nc -z localhost 8080; then
              echo "noVNC 已启动"
              break
            fi
            echo "等待中 ($i)..."
            sleep 1
          done
      - name: Run Time Adder Script 
        run: |
          mkdir -p "$GITHUB_WORKSPACE/.tmp"
          export TMPDIR="$GITHUB_WORKSPACE/.tmp"
          echo "Using TMPDIR=$TMPDIR"
          export DISPLAY=:1
          echo "Using DISPLAY=$DISPLAY"
          source .venv/bin/activate
          python main.py

      - name: Upload error artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
